services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_:/data/db
      - /Users/yubin/Documents/git/spring_multi_module/scripts/mongo-keyfile:/opt/key/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1121
      - MONGO_INITDB_DATABASE=ALGoDB
    command: >
      --replSet rs0
      --auth
      --keyFile /opt/key/mongo-keyfile
      --bind_ip_all

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo2_:/data/db
      - /Users/yubin/Documents/git/spring_multi_module/scripts/mongo-keyfile:/opt/key/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1121
      - MONGO_INITDB_DATABASE=ALGoDB
    command: >
      --replSet rs0
      --auth
      --keyFile /opt/key/mongo-keyfile
      --bind_ip_all

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - mongo3_:/data/db
      - /Users/yubin/Documents/git/spring_multi_module/scripts/mongo-keyfile:/opt/key/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1121
      - MONGO_INITDB_DATABASE=ALGoDB
    command: >
      --replSet rs0
      --auth
      --keyFile /opt/key/mongo-keyfile
      --bind_ip_all

volumes:
  mongo1_:
  mongo2_:
  mongo3_:
