services:
  mongo1:
    image: mongo:6.0
    hostname: mongo1
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo1_:/data/db
      - ./mongodb.key:/etc/mongodb.key
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1121
      - MONGO_INITDB_DATABASE=ALGoDB
    command: >
      mongod --replSet rs0 
      --keyFile /etc/mongodb.key 
      --bind_ip_all

  mongo2:
    image: mongo:6.0
    hostname: mongo2
    container_name: mongo2
    restart: always
    depends_on:
      - mongo1
    ports:
      - "27018:27017"
    volumes:
      - mongo2_:/data/db
      - ./mongodb.key:/etc/mongodb.key
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1121
      - MONGO_INITDB_DATABASE=ALGoDB
    command: >
      mongod --replSet rs0 
      --keyFile /etc/mongodb.key 
      --bind_ip_all

  mongo3:
    image: mongo:6.0
    hostname: mongo3
    container_name: mongo3
    restart: always
    depends_on:
      - mongo2
    ports:
      - "27019:27017"
    volumes:
      - mongo3_:/data/db
      - ./mongodb.key:/etc/mongodb.key
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1121
      - MONGO_INITDB_DATABASE=ALGoDB
    command: >
      mongod --replSet rs0 
      --keyFile /etc/mongodb.key 
      --bind_ip_all

volumes:
  mongo1_:
  mongo2_:
  mongo3_:

networks:
  mongo-cluster:
    external: true
    name: mongoCluster